baseURL = "https://yute.com/"
languageCode = "en-us"
copyright = "Creative Commons"
title = "Un mixto por favor"
theme = "indigo"

[params]
  Author = "álvaro"
  Description = "álvaro's personal rumblings"
  Subtitle = "álvaro's personal rumblings"
  Avatar = "images/site-logo.svg"
  Biography = "A short description, a few sentences describing the author. Set the 'ShowBio' parameter to false to hide this."
  ShowBio = false
  PermalinkText = "🔗"